### ISSUE TITLE
File not found when verify contract 

### ISSUE THREAD

**Issue by ctb0k33** [foundry-rs/book#1226]
I try to deploy my contract using UUPS proxy (ERC1967). But when i run the script, foundry can't found the file.

Error message: "Details: `Fail - Unable to verify. Solidity Compilation Error: Source "lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/interfaces/draft-IERC1822.sol" not found: File not found. Searched the following locations: "".`
Contract failed to verify."

I already click on the source and the file is still there. I also update my foundry version but it still not work.

Here is my foundry.toml file:
```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read", path = "./broadcast" }, {access = "read", path = "./Images/"}]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
```
