### ISSUE TITLE
Document test matching in `foundry.toml`

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#235]
It is now possible to split your tests into different suites using `foundry.toml` by specifying test matchers under different profiles. See https://github.com/foundry-rs/foundry/pull/1378

An example would be splitting forking and non-forking tests:

```toml
[default]
# ...

[unit-tests]
path_pattern = "test/unit/**/*.t.sol"

[fork-tests]
path_pattern = "test/fork/**/*.t.sol"
eth_rpc_url = "..."
```
