### ISSUE TITLE
document suggestion of "lite" mode for faster compilation

### ISSUE THREAD

**Issue by mds1** [foundry-rs/book#709]
I'm not sure what section of the book to put this in, so dropping it in this issue for now, but per https://github.com/foundry-rs/forge-std/issues/225#issuecomment-1321298301 we may want to add something like this to the book:

--------

Many projects use the solc optimizer, either directly or with via-ir. A config file may look like this for regular compilation:

```toml
[profile.default]
solc-version = "0.8.17"
optimizer = true
optimizer-runs = 10_000_000
```

Or like this for via-ir:

```toml
[profile.default]
solc-version = "0.8.17"
via_ir = true
```

The optimizer can significantly slow down compilation speeds, so one trick is to have a `lite` profile that has the optimizer off and use this for development. The updated config file for regular compilation may look like this:

```toml
[profile.default]
solc-version = "0.8.17"
optimizer = true
optimizer-runs = 10_000_000

[profile.lite]
optimizer = false
```

Or like this for via-ir:

```toml
[profile.default]
solc-version = "0.8.17"
via_ir = true

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''
```

(note that there are additional optimizer details you can configure, see [here](https://book.getfoundry.sh/reference/forge/forge-build?highlight=optimizersteps#additional-optimizer-settings) for more info)

Running `forge build` (or `test` or `script`) still uses the standard profile, so by default a `forge script` invocation will deploy your contracts with the production setting. Running `FOUNDRY_PROFILE=lite forge build` (and again, same for test/script) will use the lite profile to reduce compilation times
